site_name: Sindri
site_url: https://dimanu-py.github.io/sindri
site_description: >
  A tool to help you create value objects, validate domain logic, ensure data integrity 
  and generate test data in your Python applications.
repo_name: sindripy
repo_url: https://github.com/dimanu-py/sindri
extra:
  homepage: home/
extra_css:
  - assets/extra.css
plugins:
  - search
  - tags
  - section-index
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
  - attr_list:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
  - pymdownx.superfences:
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
    logo: logo
  features:
    - navigation.path
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.indexes
    - navigation.tracking
    - content.code.annotate
    - toc.follow
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: '#B4BEFE'
      accent: '#FAB387'
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: '#B4BEFE'
      accent: '#FAB387'
nav:
  - Home:
      - home/index.md
      - Getting Started: home/getting_started.md
      - Navigation Guide: home/navigation_guide.md
      - Contributing Guide: home/contributing_guide.md
      - Security: home/security.md
  - Value Object:
      - value_objects/index.md
      - Built-in Value Objects: value_objects/built_in_vo.md
      - Validation Mechanism: value_objects/validation.md
      - Customizing Value Objects: value_objects/customizing_vo.md
      - Aggregate Roots: value_objects/aggregate_roots.md
  - Object Mother:
      - object_mothers/index.md
      - Built-in Mothers: object_mothers/built_in_mothers.md
      - Customizing Mothers: object_mothers/customizing_mothers.md
